### ISSUE TITLE
Couldn't lock the profile

### ISSUE THREAD

**Issue by andis777** [LING-0001/Sign-Language-Unity-Android-Demo#1]
Hello i'm build apk, debug say -  " Couldn't lock the profile file /data/user/0/com.android.handtalk/files/iflytek/idata/cache/oat/9e1d104f4c0b40b6acd687cfc7045f60.zip.cur.prof: Failed to open file '/data/user/0/com.android.handtalk/files/iflytek/idata/cache/oat/9e1d104f4c0b40b6acd687cfc7045f60.zip.cur.prof': No such file or directory
    Could not forcefully load profile /data/user/0/com.android.handtalk/files/iflytek/idata/cache/oat/9e1d104f4c0b40b6acd687cfc7045f60.zip.cur.prof"

**Comment by LING-0001** [comment]
Sorry I only saw this issue now, some absolute paths need to be downloaded by yourself to change the Unity software.
